<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>845ab4e2-6e0b-4e53-aed0-952200740d9e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.63" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.22" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="tesseract-data\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tesseract-data\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tesseract-data\rus.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tesseract-data\ukr.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
