// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatrickBotman.Common.Persistence;

#nullable disable

namespace PatrickBotman.Common.Migrations
{
    [DbContext(typeof(PatrickBotmanContext))]
    [Migration("20231226113104_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatrickBotman.Common.Persistence.Entities.Blacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("GifId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GifId");

                    b.ToTable("Blacklists");
                });

            modelBuilder.Entity("PatrickBotman.Common.Persistence.Entities.Gif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gifs");
                });

            modelBuilder.Entity("PatrickBotman.Common.Persistence.Entities.GifFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GifFiles");
                });

            modelBuilder.Entity("PatrickBotman.Common.Persistence.Entities.Blacklist", b =>
                {
                    b.HasOne("PatrickBotman.Common.Persistence.Entities.Gif", "Gif")
                        .WithMany("Blacklist")
                        .HasForeignKey("GifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gif");
                });

            modelBuilder.Entity("PatrickBotman.Common.Persistence.Entities.Gif", b =>
                {
                    b.Navigation("Blacklist");
                });
#pragma warning restore 612, 618
        }
    }
}
