version: "3"

services:
  bot:
    container_name: patrick-botman

    build:
      context: .
      dockerfile: ./PatrickBotman.Bot/Dockerfile
    ports:
      - "5000:80"
    environment:
      COMPOSE_PROJECT_NAME: patrick_botman
      ASPNETCORE_ENVIRONMENT: "Docker"     
      ConnectionStrings__PostgreConn: ${POSTGRE_CONN}
      GiphyConfiguration__ApiToken: ${GIPHY_API_TOKEN}
      BotConfiguration__BotToken: ${TG_BOT_TOKEN}
      BotConfiguration__HostAddress: ${TG_BOT_HOSTADDRESS}

    restart: always